# -*- mode: ruby -*-
# vi: set ft=ruby :

WINDOWS_SERVER="StefanScherer/windows_2019"
KALI="kalilinux/rolling"
UBUNTU="ubuntu/jammy64"

Vagrant.configure("2") do |config|

  config.vm.define "purple" do |lab|
    lab.vm.box = KALI
    lab.vm.hostname = "purple"
    lab.vm.network "private_network", ip: "192.168.10.50"
    lab.vm.network "forwarded_port", guest: 8080, host: 8080
    lab.vm.network "forwarded_port", guest: 8888, host: 8888
    lab.vm.disk :disk, size:"20GB", primary: true
    lab.vm.provider "virtualbox" do |vb|
      vb.memory = 5000
      vb.cpus = 2
      vb.name = "purple"
      vb.gui = false
    end

    #lab.vm.provision "shell", path: "./scripts/purple.sh", privileged: true
  end

  config.vm.define "splunk" do |lab|
    lab.vm.box = UBUNTU
    lab.vm.hostname = "splunk"
    lab.vm.network "private_network", ip: "192.168.10.100"
    lab.vm.network "forwarded_port", guest: 8000, host: 8000
    lab.vm.disk :disk, size:"20GB", primary: true
    lab.vm.provider "virtualbox" do |vb|
      vb.memory = 3000
      vb.cpus = 2
      vb.name = "splunk"
      vb.gui = false
    end
  end

  config.vm.define "windows2019" do |lab|
    lab.vm.box = WINDOWS_SERVER
    lab.vm.hostname = "windows2019"
    lab.vm.communicator = "winrm"
    lab.vm.network "private_network", ip: "192.168.10.20"
    lab.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    lab.vm.disk :disk, size:"20GB", primary: true
    lab.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "windows2019"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
	lab.vm.provision "shell", path: "./scripts/windows_server.ps1", privileged: true
  end
  	
  
 end
