---
- name: Build and Run Docker Container from Dockerfile
  shell: |
      docker build -t caldera .
  args:
      executable: /bin/bash

- name: Run container Caldera
  shell: |
      docker run -it -d --name caldera -p 8888:8888 caldera
  args:
      executable: /bin/bash

- name: Check docker container
  shell: |
      docker ps -q --filter "name=caldera"
  register: docker_container_check

- name: check if run in port 8888
  debug:
      msg: "Docker container is running on port 8888"
  when: docker_container_check.stdout != ""
