---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG Key
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | \
    sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
  register: gpg_output
  ignore_errors: yes

- name: Verify Docker GPG Key
  debug:
    msg: "GPG Key Output: {{ gpg_output.stdout }}"

- name: Set up Docker repository
  shell: |
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list
  args:
    executable: /bin/bash

- name: Update package index
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker.io
    state: present

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install Docker-compose
  apt:
    name:
      - docker-compose-plugin
    state: present

- name: Update package index
  apt:
    update_cache: yes

- name: Verify Docker Installation
  command: docker --version
  register: docker_version_output
  ignore_errors: yes

- name: Print Docker Version
  debug:
    msg: "Docker Version: {{ docker_version_output.stdout }}"

- name: Verify Docker Compose Installation
  command: docker compose version
  register: docker_compose_version_output
  ignore_errors: yes

- name: Print Docker Compose Version
  debug:
    msg: "Docker Compose Version: {{ docker_compose_version_output.stdout }}"
